name: Notify home manager repo

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  notify:
    name: notify
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Github REST API Call
        env:
          CI_TOKEN: ${{ secrets.HOME_MANAGER_NOTIFY_TOKEN }}
          PARENT_REPO: wyatt-avilla/home-manager
          PARENT_BRANCH: main
          WORKFLOW_ID: 152027521
        run: |
          curl -fL --retry 3 -X POST -H "Accept: application/vnd.github.v3+json" -H "Authorization: token ${{ env.CI_TOKEN }}" https://api.github.com/repos/${{ env.PARENT_REPO }}/actions/workflows/${{ env.WORKFLOW_ID }}/dispatches -d '{"ref":"${{ env.PARENT_BRANCH }}"}'
